# coding: utf-8

"""
    Hatchet API

    The Hatchet API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing_extensions import Self


class UserLoginRequest(BaseModel):
    """
    UserLoginRequest
    
    Note: This class contains sensitive authentication data (password).
    Use secure serialization methods (to_secure_dict, to_secure_json) for logging or debugging.
    """  # noqa: E501

    email: StrictStr = Field(description="The email address of the user.")
    password: StrictStr = Field(description="The password of the user. This sensitive data is redacted in string representations.")
    __properties: ClassVar[List[str]] = ["email", "password"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        # Use the secure version to avoid exposing the password
        return pprint.pformat(self.to_secure_dict())

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    def to_secure_json(self) -> str:
        """Returns the JSON representation with sensitive data redacted"""
        return json.dumps(self.to_secure_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserLoginRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    def to_secure_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation with sensitive data redacted"""
        # Get the dictionary representation
        _dict = self.to_dict()
        
        # Redact the password
        if "password" in _dict:
            _dict["password"] = "********"
            
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserLoginRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {"email": obj.get("email"), "password": obj.get("password")}
        )
        return _obj

    def __repr__(self) -> str:
        """Ensure password is redacted in all string representations"""
        return self.to_str()