# coding: utf-8

"""
    Hatchet API

    The Hatchet API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing_extensions import Self


class CreateEventRequest(BaseModel):
    """
    CreateEventRequest
    """  # noqa: E501

    key: StrictStr = Field(description="The key for the event.")
    data: Dict[str, Any] = Field(description="The data for the event.")
    additional_metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Additional metadata for the event.",
        alias="additionalMetadata",
    )
    __properties: ClassVar[List[str]] = ["key", "data", "additionalMetadata"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    @field_validator('data', 'additional_metadata')
    @classmethod
    def validate_dict_content(cls, v: Optional[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
        """Validate dictionary content to prevent adversarial inputs."""
        if v is None:
            return v
        
        # Detect potentially harmful patterns
        cls._validate_dict_recursively(v)
        return v
    
    @classmethod
    def _validate_dict_recursively(cls, value: Any, depth: int = 0, path: str = ""):
        """Recursively validate values to prevent adversarial inputs."""
        # Prevent excessive recursion
        if depth > 20:  # Limit recursion depth
            raise ValueError(f"Maximum nesting depth exceeded at: {path}")
        
        # Handle dictionaries
        if isinstance(value, dict):
            if len(value) > 1000:  # Limit dictionary size
                raise ValueError(f"Dictionary too large at: {path}")
            
            for k, v in value.items():
                # Validate key
                if not isinstance(k, str):
                    raise ValueError(f"Dictionary keys must be strings at: {path}")
                if len(k) > 256:  # Limit key length
                    raise ValueError(f"Dictionary key too long at: {path}")
                
                # Recursively validate value
                new_path = f"{path}.{k}" if path else k
                cls._validate_dict_recursively(v, depth + 1, new_path)
        
        # Handle lists
        elif isinstance(value, list):
            if len(value) > 10000:  # Limit list size
                raise ValueError(f"List too large at: {path}")
            
            for i, item in enumerate(value):
                new_path = f"{path}[{i}]"
                cls._validate_dict_recursively(item, depth + 1, new_path)
        
        # Handle strings
        elif isinstance(value, str):
            if len(value) > 100000:  # Limit string length
                raise ValueError(f"String too long at: {path}")

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateEventRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateEventRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "key": obj.get("key"),
                "data": obj.get("data"),
                "additionalMetadata": obj.get("additionalMetadata"),
            }
        )
        return _obj