# coding: utf-8

"""
    Hatchet API

    The Hatchet API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
from enum import Enum

from typing_extensions import Self


class WorkflowKind(str, Enum):
    """
    WorkflowKind
    """

    """
    allowed enum values
    """
    FUNCTION = "FUNCTION"
    DURABLE = "DURABLE"
    DAG = "DAG"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WorkflowKind from a JSON string"""
        value = json.loads(json_str)
        if not isinstance(value, str):
            raise TypeError(f"Expected string value, got {type(value).__name__}")
        
        valid_values = [e.value for e in cls]
        if value not in valid_values:
            raise ValueError(f"Invalid WorkflowKind value: {value}. Expected one of: {valid_values}")
        
        return cls(value)